language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: L5_VER=4
    - php: 7.1
      env: L5_VER=5
    - php: 7.1
      env: L5_VER=6
    - php: 7.1
      env: L5_VER=7
    - php: 7.2
      env: L5_VER=4
    - php: 7.2
      env: L5_VER=5
    - php: 7.2
      env: L5_VER=6
    - php: 7.2
      env: L5_VER=7
    - php: 7.3
      env: L5_VER=4
    - php: 7.3
      env: L5_VER=5
    - php: 7.3
      env: L5_VER=6
    - php: 7.3
      env: L5_VER=7

script:
  - vendor/bin/phpunit

before_install:
  - composer require "illuminate/support:5.${L5_VER}.*" --no-update -v
  - composer require "illuminate/console:5.${L5_VER}.*" --no-update -v
  - composer require "orchestra/testbench:3.${L5_VER}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "mmOXKdWf6VwJjom86dxsPE/+CCMkrqQV+hr1h8gmq51agybDeSHIH2dmWO+BVZd1IgtlaXEkxmM03t288md6jVF1kNphzCQc9YjDxDuGvCcrsPh//1fxOm4heH5Glm6yWB0h9/3o2njIiHpQZjt8EMwhpPPxfp5d97dTJjwT7vLRUtX8Jt82ofM1R6jPbL70/FtxuAAb8AwJfFewhCuIHuR9KizPEYl2Y+LfSaW8a5JP5ut29rba1jfNMmErTTrdCmxbOQl8H0t3Wj1cOse1wMeGMQFtPtAvjN3qHqLQJgJQHDCEvugrbU7EhOpqE5kwLhFlhfIGO/53KMVaSS/8D+HVKVOk3EXlnkBUsp94vxbSXRrs/J/1xmEDqmX6vegM+SdVL0lWJ3YLztW7YVYJZ2c+Ax5B1KXpNJS904MDySqnvHxJ9Cga3eCZkNVCfUNTaYZfJ7DHVam3iGhkEtChHeua+8EUDLYJu9Re0NOM4Q41EovrWOASH4yKo8Pjo+nRGrdrosRrEGgFOSjCZJD5/SRMEbw1xbMOAFx5Sdl0DFBRKTd5TwL/+6fERA0iFHOo5UTWOn0nqSkHGqxXb0rtSt1vVO2rsNYUQ7hFwrNKBUNtt9P+6Pyu8ljI4DnydY9616a3mq4bl9k3bGszFwUH8on4RRJLtiYst/uSJCqts5E="
